/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.6.0.83.4 */
/* Module Version: 7.5 */
/* Thu May 04 13:13:57 2017 */

/* parameterized module instance */
regbank_lattice __ (.DataInA( ), .DataInB( ), .AddressA( ), .AddressB( ), 
    .ClockA( ), .ClockB( ), .ClockEnA( ), .ClockEnB( ), .WrA( ), .WrB( ), 
    .ResetA( ), .ResetB( ), .QA( ), .QB( ));
